Modbus fixes.   Fixed new modbus server code (what was I thinking with the O(N^2) search?).   Fixed other Modbus tests to use port 1502 or port 2502.   Added Modbus tests to test scripts and CI.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -221,10 +221,29 @@ jobs:
       run: |
         cd ${{ env.DIST }}
         echo "start up simulator..."
-        ${{ env.DIST }}/modbus_server &
+        ${{ env.DIST }}/modbus_server --listen 127.0.0.1:1502 --listen 127.0.0.1:2502 > modbus_server.log 2>&1 &
         sleep 2
+        
+        echo "test short reconnect with Modbus"
+        ${{ env.DIST }}/test_reconnect 3
+
+        echo "test long reconnect with Modbus"
+        ${{ env.DIST }}/test_reconnect 10
+
+        echo "test thread stress Modbus"
+        ${{ env.DIST }}/thread_stress 10 'protocol=modbus-tcp&gateway=127.0.0.1:1502&path=0&elem_count=2&name=hr10'
+
         echo "test Modbus callbacks and read/write"
         ${{ env.DIST }}/test_callback_ex_modbus
+
+        echo "test Modbus multiple connections with timeouts"
+        ${{ env.DIST }}/test_modbus_multiple > test_modbus_multiple.log 2>&1
+        if grep -q "thread(5)" test_modbus_multiple.log; then
+          echo "FAILURE: found thread(5) in log file"
+          exit 1
+        else
+          echo "OK: no thread(5) found in log file"
+        fi
         echo "shut down server."
         killall modbus_server -TERM &> /dev/null
         sleep 3
@@ -439,6 +458,36 @@ jobs:
         cd ${{ env.DIST }}
         echo "Test reconnect after outage"
         ${{ env.DIST }}/test_reconnect_after_outage ./ab_server
+
+    - name: Test Modbus
+      run: |
+        cd ${{ env.DIST }}
+        echo "start up simulator..."
+        ${{ env.DIST }}/modbus_server --listen 127.0.0.1:1502 --listen 127.0.0.1:2502 > modbus_server.log 2>&1 &
+        sleep 2
+        echo "test short reconnect with Modbus"
+        ${{ env.DIST }}/test_reconnect 3
+
+        echo "test long reconnect with Modbus"
+        ${{ env.DIST }}/test_reconnect 10
+
+        echo "test thread stress Modbus"
+        ${{ env.DIST }}/thread_stress 10 'protocol=modbus-tcp&gateway=127.0.0.1:1502&path=0&elem_count=2&name=hr10'
+
+        echo "test Modbus callbacks and read/write"
+        ${{ env.DIST }}/test_callback_ex_modbus
+
+        echo "test Modbus multiple connections with timeouts"
+        ${{ env.DIST }}/test_modbus_multiple > test_modbus_multiple.log 2>&1
+        if grep -q "thread(5)" test_modbus_multiple.log; then
+          echo "FAILURE: found thread(5) in log file"
+          exit 1
+        else
+          echo "OK: no thread(5) found in log file"
+        fi
+        echo "shut down server."
+        killall modbus_server -TERM &> /dev/null
+        sleep 3
 
     - name: Create ZIP artifacts
       run: |
